augment: false
batch_size: 64
beta1: 0.93
beta2: 0.98
d_ff: 1024
d_model: 256
d_qkv: 64
data_type: mfcc
dataset_name: MODMA
dilation: 8
drop_rate: 0.1
epochs: 150
feature_dim: 39
filters: 39
gamma: 0.3
initial_lr: 0.05
is_cluster: false
is_mask: false
is_weight: true
kernel_size: 2
load_weight: false
lr: 0.0005
mode: train
model_name: ' '
model_type: ''
n_head: 8
n_layer: 3
num_class: 6
optimizer_type: 2
order: 3
pretrain_model_path: iemocap_pretrain.pt
random_seed: 34
save: true
scheduler_type: 1
seq_len: 100
smooth: true
spilt_rate:
- 0.8
- 0.1
- 0.1
step_size: 30
version: V2
warmup: 400
weight_decay: 0.5
