augment: false
batch_size: 64
beta1: 0.93
beta2: 0.98
d_ff: 1024
d_model: 256
d_qkv: 64
data_type: mfcc
dilation: 8
drop_rate: 0.1
epochs: 60
feature_dim: 39
filters: 39
gamma: 0.3
initial_lr: 0.08
is_mask: false
is_weight: true
kernel_size: 2
load_weight: false
lr: 0.0002
mode: train
model_name: ' '
n_head: 8
n_layer: 2
num_class: 2
order: 3
plus_scores: false
random_seed: 34
save: false
scheduler_type: 1
seq_len: 313
smooth: true
step_size: 30
warmup: 300
weight_decay: 0.1
